[tasks.default]
alias = "install"

[tasks.install]
script_runner = "@shell"
command = "mv"
args = ["target/debug/logjam", "portable/"]
dependencies = ["build", "create-portable"]

[tasks.create-portable]
script_runner = "@shell"
command = "mkdir"
args = ["portable"]