[tasks.default]
alias = "install"

[tasks.install]
script_runner = "@shell"
command = "mv"
args = ["target/debug/logjam", "portable/"]
dependencies = ["build", "create-portable", "remove"]

[tasks.remove]
script_runner = "@shell"
command = "rm"
args = ["portable/logjam"]

[tasks.create-portable]
ignore_errors = true
script_runner = "@shell"
command = "mkdir"
args = ["portable"]