[tasks.default]
dependencies = ["move-assets"]

[tasks.move-assets]
script_runner = "@rust"
script = '''
use std::{env, fs, path::Path};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let assets_path = env::var("CARGO_MAKE_WORKING_DIRECTORY")?;
    let target_path = env::var("CARGO_MAKE_CRATE_TARGET_DIRECTORY")?;

    let source_path = Path::new(&assets_path).join("assets");
    let destination_path = Path::new(&target_path).join("portable");

    println!("Copying assets from {:?} to {:?}", source_path, destination_path);
	fs::create_dir_all(&destination_path)?;

    for entry in fs::read_dir(source_path)? {
        let file = entry?;
        let src = file.path();
        let dst = destination_path.join(file.file_name());

        println!("Copying {:?} -> {:?}", src, dst);
        fs::copy(&src, &dst)?;
    }

    Ok(())
}
'''